"""Utilities for AbacusSummit HOD tabulation preparation."""

_EXPORTS = {
    "apply_rsd": (".rsd", "apply_rsd"),
    "available_hod_models": (".hod", "available_hod_models"),
    "build_mass_tabulation": (".paircounts", "build_mass_tabulation"),
    "compute_paircounts_from_prepared": (".paircounts", "compute_paircounts_from_prepared"),
    "evaluate_hod": (".hod", "evaluate_hod"),
    "FitDataVector": (".fitting", "FitDataVector"),
    "FitParameter": (".fitting", "FitParameter"),
    "HODFittingProblem": (".fitting", "HODFittingProblem"),
    "HODDerivedTabulator": (".derived", "HODDerivedTabulator"),
    "HODLinearBiasTabulator": (".linear_bias", "HODLinearBiasTabulator"),
    "LinearBiasResult": (".linear_bias", "LinearBiasResult"),
    "infer_abacus_cosmology_index": (".linear_bias", "infer_abacus_cosmology_index"),
    "linear_matter_xi_abacus": (".linear_bias", "linear_matter_xi_abacus"),
    "write_mcmc_derived": (".derived", "write_mcmc_derived"),
    "write_optimization_derived": (".derived", "write_optimization_derived"),
    "ObservableSpec": (".fitting", "ObservableSpec"),
    "NumberDensityConstraint": (".fitting", "NumberDensityConstraint"),
    "ObservableDataSegment": (".fitting", "ObservableDataSegment"),
    "load_fitting_problem_from_config": (".fitting", "load_fitting_problem_from_config"),
    "ChainSamples": (".plotting", "ChainSamples"),
    "OptimizationResult": (".plotting", "OptimizationResult"),
    "ObservableFitBand": (".plotting", "ObservableFitBand"),
    "HODBand": (".plotting", "HODBand"),
    "ObservableDataPoints": (".plotting", "ObservableDataPoints"),
    "ParameterStats": (".plotting", "ParameterStats"),
    "FitPlotData": (".plotting", "FitPlotData"),
    "fit_output_dir_from_config": (".plotting", "fit_output_dir_from_config"),
    "fit_output_prefix_from_config": (".plotting", "fit_output_prefix_from_config"),
    "pocomc_chain_path_from_config": (".plotting", "pocomc_chain_path_from_config"),
    "pocomc_derived_chain_path_from_config": (".plotting", "pocomc_derived_chain_path_from_config"),
    "optimization_result_path_from_config": (".plotting", "optimization_result_path_from_config"),
    "theory_vector_path_from_config": (".plotting", "theory_vector_path_from_config"),
    "load_plotting_problem": (".plotting", "load_plotting_problem"),
    "load_fit_plot_data": (".plotting", "load_fit_plot_data"),
    "load_chain": (".plotting", "load_chain"),
    "load_chain_from_config": (".plotting", "load_chain_from_config"),
    "load_chains": (".plotting", "load_chains"),
    "load_optimization_result": (".plotting", "load_optimization_result"),
    "load_optimization_result_from_config": (".plotting", "load_optimization_result_from_config"),
    "getdist_samples": (".plotting", "getdist_samples"),
    "plot_triangle": (".plotting", "plot_triangle"),
    "fit_bands_from_fit": (".plotting", "fit_bands_from_fit"),
    "fit_bands_from_fits": (".plotting", "fit_bands_from_fits"),
    "fit_bands_from_theory_vector": (".plotting", "fit_bands_from_theory_vector"),
    "fit_bands_from_optimization": (".plotting", "fit_bands_from_optimization"),
    "load_theory_vector": (".plotting", "load_theory_vector"),
    "plot_fit_bands": (".plotting", "plot_fit_bands"),
    "plot_fit": (".plotting", "plot_fit"),
    "plot_fits": (".plotting", "plot_fits"),
    "plot_fit_from_config": (".plotting", "plot_fit_from_config"),
    "hod_bands_from_fit": (".plotting", "hod_bands_from_fit"),
    "hod_bands_from_fits": (".plotting", "hod_bands_from_fits"),
    "plot_hod_bands": (".plotting", "plot_hod_bands"),
    "plot_hod": (".plotting", "plot_hod"),
    "plot_hods": (".plotting", "plot_hods"),
    "plot_derived_parameters": (".plotting", "plot_derived_parameters"),
    "plot_joint_grid": (".plotting", "plot_joint_grid"),
    "load_config": (".config", "load_config"),
    "merge_configs": (".config", "merge_configs"),
    "HODClusteringTabulator": (".clustering", "HODClusteringTabulator"),
    "write_hmf": (".hmf", "write_hmf"),
    "read_hmf": (".hmf", "read_hmf"),
    "hod_satellite_number_density": (".hmf", "hod_satellite_number_density"),
    "hod_satellite_median_log10_host_mass": (".hmf", "hod_satellite_median_log10_host_mass"),
    "hod_satellite_median_host_mass": (".hmf", "hod_satellite_median_host_mass"),
    "hod_satellite_fraction": (".hmf", "hod_satellite_fraction"),
    "hod_number_density": (".hmf", "hod_number_density"),
    "hod_derived_quantities": (".hmf", "hod_derived_quantities"),
    "hod_central_number_density": (".hmf", "hod_central_number_density"),
    "hod_central_median_log10_host_mass": (".hmf", "hod_central_median_log10_host_mass"),
    "hod_central_median_host_mass": (".hmf", "hod_central_median_host_mass"),
    "hmf_from_config": (".hmf", "hmf_from_config"),
    "find_hmf_file": (".hmf", "find_hmf_file"),
    "find_paircount_file": (".paircounts", "find_paircount_file"),
    "validate_hmf_file": (".hmf", "validate_hmf_file"),
    "validate_hmf_file_for_config": (".hmf", "validate_hmf_file_for_config"),
    "validate_logm_edges": (".paircounts", "validate_logm_edges"),
    "validate_paircount_file": (".paircounts", "validate_paircount_file"),
    "radial_bin_edges": (".paircounts", "radial_bin_edges"),
    "resolve_paircount_path_from_config": (".paircounts", "resolve_paircount_path_from_config"),
    "compute_hmf_from_prepared": (".hmf", "compute_hmf_from_prepared"),
    "build_hmf_from_prepared": (".hmf", "build_hmf_from_prepared"),
    "HODDerivedQuantities": (".hmf", "HODDerivedQuantities"),
    "HaloMassFunction": (".hmf", "HaloMassFunction"),
    "galaxy_correlation_from_config": (".clustering", "galaxy_correlation_from_config"),
    "galaxy_correlation_from_paircounts": (".clustering", "galaxy_correlation_from_paircounts"),
    "galaxy_cross_correlation_from_paircounts": (".clustering", "galaxy_cross_correlation_from_paircounts"),
    "hod_model_parameters": (".hod", "hod_model_parameters"),
    "hod_weights_for_paircounts": (".clustering", "hod_weights_for_paircounts"),
    "load_prepared_catalog": (".paircounts", "load_prepared_catalog"),
    "load_prepared_binned_catalog": (".paircounts", "load_prepared_binned_catalog"),
    "nfw_enclosed_fraction": (".nfw", "nfw_enclosed_fraction"),
    "paircounts_from_config": (".paircounts", "paircounts_from_config"),
    "prepare_all_slabs": (".prepare", "prepare_all_slabs"),
    "prepare_from_config": (".prepare", "prepare_from_config"),
    "prepare_slab": (".prepare", "prepare_slab"),
    "projected_wp": (".clustering", "projected_wp"),
    "read_paircounts": (".clustering", "read_paircounts"),
    "random_geometry_factor": (".clustering", "random_geometry_factor"),
    "sample_nfw_offsets": (".nfw", "sample_nfw_offsets"),
    "sample_nfw_radii": (".nfw", "sample_nfw_radii"),
    "smu_multipoles": (".clustering", "smu_multipoles"),
    "velzspace_to_kms": (".rsd", "velzspace_to_kms"),
    "wrap_positions": (".rsd", "wrap_positions"),
}

__all__ = sorted(_EXPORTS)


def __getattr__(name):
    if name not in _EXPORTS:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    import importlib

    module_name, attr_name = _EXPORTS[name]
    module = importlib.import_module(module_name, __name__)
    value = getattr(module, attr_name)
    globals()[name] = value
    return value
